import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/doctor.dart';
import '../models/prescription.dart';

class PrescriptionPdfService {
  const PrescriptionPdfService._();

  static Future<Uint8List> build({
    required Doctor doctor,
    required Prescription prescription,
  }) async {
    final pdf = pw.Document();
    final date = DateFormat('MMM d, yyyy').format(prescription.createdAt);
    final followUp = DateFormat(
      'MMM d, yyyy',
    ).format(prescription.followUpDate);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'MedLink',
                        style: pw.TextStyle(
                          fontSize: 26,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.blue700,
                        ),
                      ),
                      pw.Text('Digital Prescription'),
                    ],
                  ),
                  pw.Text(date),
                ],
              ),
              pw.SizedBox(height: 24),
              _sectionTitle('Doctor'),
              pw.Text(doctor.name, style: _bold()),
              pw.Text('${doctor.specialty} | ${doctor.qualification}'),
              pw.Text(doctor.clinicName),
              pw.SizedBox(height: 18),
              _sectionTitle('Patient'),
              pw.Text(prescription.patientName, style: _bold()),
              pw.SizedBox(height: 18),
              _sectionTitle('Diagnosis'),
              pw.Text(prescription.diagnosis),
              pw.SizedBox(height: 18),
              _sectionTitle('Medicines'),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey300),
                columnWidths: const {
                  0: pw.FlexColumnWidth(2),
                  1: pw.FlexColumnWidth(1.4),
                  2: pw.FlexColumnWidth(1.4),
                  3: pw.FlexColumnWidth(1.2),
                },
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(
                      color: PdfColors.grey200,
                    ),
                    children: [
                      _cell('Medicine', bold: true),
                      _cell('Dosage', bold: true),
                      _cell('Frequency', bold: true),
                      _cell('Duration', bold: true),
                    ],
                  ),
                  ...prescription.medicines.map(
                    (medicine) => pw.TableRow(
                      children: [
                        _cell(medicine.name),
                        _cell(medicine.dosage),
                        _cell(medicine.frequency),
                        _cell(medicine.duration),
                      ],
                    ),
                  ),
                ],
              ),
              pw.SizedBox(height: 18),
              _sectionTitle('Instructions'),
              pw.Text(prescription.instructions),
              pw.SizedBox(height: 18),
              _sectionTitle('Follow-up'),
              pw.Text(followUp),
              pw.Spacer(),
              pw.Divider(),
              pw.Text(
                'Generated by MedLink. This is a portfolio demo document.',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _sectionTitle(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.blue700,
        ),
      ),
    );
  }

  static pw.TextStyle _bold() {
    return pw.TextStyle(fontWeight: pw.FontWeight.bold);
  }

  static pw.Widget _cell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(text, style: bold ? _bold() : null),
    );
  }
}
